### ISSUE TITLE
Class Not found exception

### ISSUE THREAD

**Issue by katariarahul** [alexa/alexa-skills-kit-java#42]
Hi,
i am working on to setup scorekeeper for alexa from the link
https://github.com/amzn/alexa-skills-kit-java/blob/master/samples/src/main/java/scorekeeper/README.md.

I have setup everything as mentioned in the link but while doing testing from Service Simulator, i am getting following error in lambda (CloudWatch)

Class not found: scorekeeper.ScoreKeeperSpeechletRequestStreamHandler: class java.lang.ClassNotFoundException
java.lang.ClassNotFoundException: scorekeeper.ScoreKeeperSpeechletRequestStreamHandler
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)

Can you please guide in getting this resolve. Thanks.

**Comment by apadki** [comment]
Sample is not in the build in pom, the quickest is to move the package under src, thats how I got it working.

**Comment by matiaslb** [comment]
I've ran into the same issue recently and, after a lot of head scratching, eventually realized it was due to the permissions of the files inside my zip file. I had set up my umask in zsh so that only my user and the group had read permissions on files, i.e.: the permissions for the classes and libraries inside the zip were all set to 640.

**Comment by sungolivia** [comment]
Do you still have this issue? If so, have you specified scorekeeper.ScoreKeeperSpeechletRequestStreamHandler in Handler section within Function code in Lambda?

**Comment by sungolivia** [comment]
Closing due to inactivity but please feel free to reopen if this issue persists!
