### ISSUE TITLE
hello i try to develope a alexa skill using this example but i get this error

### ISSUE THREAD

**Issue by Pemboura** [alexa/alexa-skills-kit-java#56]
org/slf4j/LoggerFactory: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at mensathm.MensaThmSpeechlet.<clinit>(MensaThmSpeechlet.java:25)
	at mensathm.MensaThmSpeechletRequestStreamHandler.<init>(MensaThmSpeechletRequestStreamHandler.java:28)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

**Comment by Vest** [comment]
It might happen that your project doesn't have the library slf4j in the build and/or class path. If you use Maven, please be sure that you have this library in pom.xml. E.g.
```xml
	<dependency>
		<groupId>org.slf4j</groupId>
		<artifactId>slf4j-api</artifactId>
		<version>[1.7,)</version>
		<scope>provided</scope>
	</dependency>
```
If you tell few words about your project and the way how you run it, somebody will give you a better answer.
p.s. please rename the issue and put more info into the description text. It doesn't look nice.

**Comment by Pemboura** [comment]
thx for it is Work!
now i try to write a sample Methode that alexa can ask me to choice one city. i just definit 2 cities in Slot types, but i get this failure ich i work it.
" the response is invalid" and alexa app tell that the response can not be null.
i need some help
thx

**Comment by Vest** [comment]
I appreciate your feedback. It means that the current issue is not an issue anymore, and you would better close it to avoid any possible confusion for everyone.

With your question, please ask it in the corresponding forums. E.g. [here](https://forums.developer.amazon.com/spaces/165/alexa.html). I do not think that using the "issues" tab as a forum is a good idea. Sorry.

Regarding your second question: I suggest you to check that you send a response object rather than null. Try to start from the simple example: one intent, one response, no processing and then increase the complexity of the code. E.g.

```java
@Override
public SpeechletResponse onIntent(IntentRequest request, Session session) throws SpeechletException {
    String speechText = "Hello Vest! I like your reply.";
    SimpleCard card = new SimpleCard();
    card.setTitle("Hello World");
    card.setContent(speechText);

    PlainTextOutputSpeech speech = new PlainTextOutputSpeech();
    speech.setText(speechText);

    return SpeechletResponse.newTellResponse(speech, card);
}
```
That's all.

**Comment by sungolivia** [comment]
Closing due to inactivity but please feel free to reopen if this issue persists!
